import Link from "next/link";
import { CircleDollarSign } from "lucide-react";
import { Card } from "@/components/ui/card";
import { CurrencyValues } from "@/components/ui/currency-values";
import type { ClientOutstandingItem } from "@/types/dashboard";

export function OutstandingClientPayments({ items, error }: { items: ClientOutstandingItem[]; error?: string }) {
  return <Card className="overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-semibold text-slate-900">Outstanding client payments</h2><p className="mt-1 text-sm text-slate-500">Positive assignment balances grouped by client and kept separate by currency.</p></div>{error ? <p className="p-5 text-sm text-red-700">{error}</p> : items.length === 0 ? <div className="flex min-h-48 flex-col items-center justify-center p-6 text-center"><CircleDollarSign aria-hidden="true" className="size-6 text-emerald-500" /><h3 className="mt-3 font-semibold text-slate-900">No client balance outstanding</h3><p className="mt-1 text-sm text-slate-500">Clients with assignments carrying a positive balance will appear here.</p></div> : <div className="overflow-x-auto"><table className="w-full min-w-[520px] text-left"><thead className="border-b border-slate-100 bg-slate-50 text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Client / Vendor</th><th className="px-4 py-3 text-right">Outstanding</th><th className="px-4 py-3 text-right">Open Assignments</th></tr></thead><tbody className="divide-y divide-slate-100">{items.map((item) => <tr key={item.contact_id} className="hover:bg-slate-50"><td className="px-4 py-3"><Link href={`/contacts/${item.contact_id}`} className="font-semibold text-indigo-700 hover:underline">{item.client_name}</Link></td><td className="px-4 py-3 text-right text-sm"><CurrencyValues values={item.outstanding} className="items-end font-semibold text-amber-700" /></td><td className="px-4 py-3 text-right"><span className="inline-flex min-w-8 justify-center rounded-md bg-slate-100 px-2 py-1 text-sm font-semibold text-slate-700">{item.open_assignments}</span><p className="mt-1 text-xs text-slate-500">{item.open_assignments === 1 ? "assignment" : "assignments"}</p></td></tr>)}</tbody></table></div>}</Card>;
}
