import Link from "next/link";
import { CircleDollarSign } from "lucide-react";
import { Card } from "@/components/ui/card";
import { formatCurrency } from "@/lib/utils/format";
import type { ClientOutstandingItem } from "@/types/dashboard";

export function OutstandingClientPayments({ items, error }: { items: ClientOutstandingItem[]; error?: string }) {
  return <Card className="overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-semibold text-slate-900">Outstanding client payments</h2><p className="mt-1 text-sm text-slate-500">Balances calculated only from payments matching each assignment currency.</p></div>{error ? <p className="p-5 text-sm text-red-700">{error}</p> : items.length === 0 ? <div className="flex min-h-48 flex-col items-center justify-center p-6 text-center"><CircleDollarSign aria-hidden="true" className="size-6 text-emerald-500" /><h3 className="mt-3 font-semibold text-slate-900">No client balance outstanding</h3><p className="mt-1 text-sm text-slate-500">Assignments with a positive same-currency balance will appear here.</p></div> : <div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left"><thead className="border-b border-slate-100 bg-slate-50 text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Assignment</th><th className="px-4 py-3">Client</th><th className="px-4 py-3 text-right">Selling</th><th className="px-4 py-3 text-right">Matching received</th><th className="px-4 py-3 text-right">Outstanding</th></tr></thead><tbody className="divide-y divide-slate-100">{items.map((item) => <tr key={item.assignment_id} className="hover:bg-slate-50"><td className="px-4 py-3"><Link href={`/assignments/${item.assignment_id}`} className="font-mono text-xs font-semibold text-indigo-700 hover:underline">{item.task_code}</Link><p className="mt-1 max-w-52 truncate text-sm text-slate-700">{item.title}</p>{item.unmatched_payment_count > 0 && <p className="mt-1 text-xs text-amber-700">{item.unmatched_payment_count} other-currency payment(s) excluded</p>}</td><td className="px-4 py-3 text-sm text-slate-600">{item.client_name ?? "Unavailable"}</td><td className="px-4 py-3 text-right text-sm text-slate-600">{formatCurrency(item.selling_price, item.currency)}</td><td className="px-4 py-3 text-right text-sm text-emerald-700">{formatCurrency(item.client_received, item.currency)}</td><td className="px-4 py-3 text-right text-sm font-semibold text-amber-700">{formatCurrency(item.client_outstanding, item.currency)}</td></tr>)}</tbody></table></div>}</Card>;
}
