import Link from "next/link";
import { ArrowRight, BriefcaseBusiness } from "lucide-react";
import { Card } from "@/components/ui/card";
import { AssignmentPriorityBadge, AssignmentStatusBadge } from "@/components/assignments/assignment-badges";
import { formatCurrency, formatDateTime } from "@/lib/utils/format";
import type { DashboardAssignment } from "@/types/dashboard";

export function RecentAssignments({ assignments, error }: { assignments: DashboardAssignment[]; error?: string }) {
  return <Card className="overflow-hidden"><div className="flex items-center justify-between gap-3 border-b border-slate-100 px-5 py-4"><div><h2 className="font-semibold text-slate-900">Recent assignments</h2><p className="mt-1 text-sm text-slate-500">Latest work added to the workspace.</p></div><Link href="/assignments" className="inline-flex shrink-0 items-center gap-1 text-sm font-semibold text-indigo-700 hover:underline">View all <ArrowRight aria-hidden="true" className="size-4" /></Link></div>{error ? <p className="p-5 text-sm text-red-700">{error}</p> : assignments.length === 0 ? <div className="flex min-h-52 flex-col items-center justify-center p-6 text-center"><BriefcaseBusiness aria-hidden="true" className="size-6 text-slate-400" /><h3 className="mt-3 font-semibold text-slate-900">No assignments yet</h3><p className="mt-1 text-sm text-slate-500">Add your first assignment to begin tracking work.</p><Link href="/assignments/new" className="mt-4 text-sm font-semibold text-indigo-700 hover:underline">Add assignment</Link></div> : <div className="divide-y divide-slate-100">{assignments.map((assignment) => <Link key={assignment.id} href={"/assignments/" + assignment.id} className="grid gap-3 px-5 py-4 transition hover:bg-slate-50 md:grid-cols-[minmax(0,1fr)_auto] md:items-center"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-xs font-semibold text-indigo-700">{assignment.task_code}</span><AssignmentStatusBadge status={assignment.status} /><AssignmentPriorityBadge priority={assignment.priority} /></div><h3 className="mt-1 truncate text-sm font-semibold text-slate-900">{assignment.title}</h3><p className="mt-1 text-xs text-slate-500">{assignment.client_name ?? "No client"} · {assignment.client_deadline ? formatDateTime(assignment.client_deadline) : "No deadline"}</p></div><p className="text-sm font-semibold text-slate-800">{formatCurrency(assignment.selling_price, assignment.currency)}</p></Link>)}</div>}</Card>;
}
