import Link from "next/link";
import { HandCoins } from "lucide-react";
import { Card } from "@/components/ui/card";
import { formatCurrency } from "@/lib/utils/format";
import type { WriterPayableItem } from "@/types/dashboard";

function writerLabel(item: WriterPayableItem) { return item.writer_names.length === 1 ? item.writer_names[0] : item.writer_names.length > 1 ? `${item.writer_names[0]} +${item.writer_names.length - 1}` : "Writer unavailable"; }
export function WriterPayables({ items, error }: { items: WriterPayableItem[]; error?: string }) {
  return <Card className="overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-semibold text-slate-900">Writer payables</h2><p className="mt-1 text-sm text-slate-500">Costs and payments are reconciled only within the same currency.</p></div>{error ? <p className="p-5 text-sm text-red-700">{error}</p> : items.length === 0 ? <div className="flex min-h-48 flex-col items-center justify-center p-6 text-center"><HandCoins aria-hidden="true" className="size-6 text-slate-400" /><h3 className="mt-3 font-semibold text-slate-900">No writer payments due</h3><p className="mt-1 text-sm text-slate-500">Positive same-currency writer balances will appear here.</p></div> : <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left"><thead className="border-b border-slate-100 bg-slate-50 text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Assignment</th><th className="px-4 py-3">Writer</th><th className="px-4 py-3 text-right">Cost</th><th className="px-4 py-3 text-right">Paid</th><th className="px-4 py-3 text-right">Payable</th></tr></thead><tbody className="divide-y divide-slate-100">{items.map((item) => <tr key={item.key} className="hover:bg-slate-50"><td className="px-4 py-3"><Link href={`/assignments/${item.assignment_id}`} className="font-mono text-xs font-semibold text-indigo-700 hover:underline">{item.task_code}</Link><p className="mt-1 max-w-48 truncate text-sm text-slate-700">{item.title}</p></td><td className="px-4 py-3 text-sm text-slate-600">{writerLabel(item)}</td><td className="px-4 py-3 text-right text-sm text-slate-600">{formatCurrency(item.worker_cost, item.currency)}</td><td className="px-4 py-3 text-right text-sm text-emerald-700">{formatCurrency(item.worker_paid, item.currency)}</td><td className="px-4 py-3 text-right text-sm font-semibold text-amber-700">{formatCurrency(item.worker_payable, item.currency)}</td></tr>)}</tbody></table></div>}</Card>;
}
