import { BarChart3 } from "lucide-react";
import { Card } from "@/components/ui/card";
import { CurrencyValues } from "@/components/ui/currency-values";
import { formatCurrency } from "@/lib/utils/format";
import type { MonthlyPerformance } from "@/types/report";

const percent = (value: number, max: number) => value <= 0 || max <= 0 ? "0%" : `${Math.max(3, value / max * 100)}%`;
export function MonthlyPerformanceChart({ months }: { months: MonthlyPerformance[] }) {
  const hasData = months.some((month) => month.work_value.length || month.client_received_inr || month.worker_paid_inr || month.expenses_inr);
  if (!hasData) return <Card className="flex min-h-56 flex-col items-center justify-center p-6 text-center"><BarChart3 aria-hidden="true" className="size-6 text-slate-400" /><h3 className="mt-3 font-semibold text-slate-900">No activity in this period</h3><p className="mt-1 text-sm text-slate-500">Choose another range or add assignments and transactions.</p></Card>;
  const maximum = Math.max(...months.flatMap((month) => [month.client_received_inr, month.worker_paid_inr, month.expenses_inr]), 1);
  return <Card className="overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-semibold text-slate-900">Monthly performance</h2><p className="mt-1 text-sm text-slate-500">Quoted work remains grouped by currency; bars show actual INR cash movement.</p><div className="mt-3 flex flex-wrap gap-4 text-xs text-slate-500"><span><i className="mr-1.5 inline-block size-2.5 rounded-sm bg-emerald-500" />INR received</span><span><i className="mr-1.5 inline-block size-2.5 rounded-sm bg-amber-500" />INR writer paid</span><span><i className="mr-1.5 inline-block size-2.5 rounded-sm bg-rose-400" />INR expenses</span></div></div><div className="overflow-x-auto px-5 pb-5 pt-6"><div className="min-w-[650px]"><div className="flex h-56 items-end gap-3 border-b border-slate-200">{months.map((month) => <div key={month.key} className="flex h-full min-w-0 flex-1 items-end justify-center gap-1" title={`${month.label}: received ${formatCurrency(month.client_received_inr, "INR")}`}><span className="w-3 rounded-t bg-emerald-500" style={{ height: percent(month.client_received_inr, maximum) }} /><span className="w-3 rounded-t bg-amber-500" style={{ height: percent(month.worker_paid_inr, maximum) }} /><span className="w-3 rounded-t bg-rose-400" style={{ height: percent(month.expenses_inr, maximum) }} /></div>)}</div><div className="mt-3 flex gap-3">{months.map((month) => { const cash = month.current_cash_position_inr; return <div key={month.key} className="min-w-0 flex-1 text-center"><p className="text-xs font-medium text-slate-500">{month.label}</p><div className="mt-1 text-xs"><CurrencyValues values={month.work_value} /></div><p className={`mt-1 text-[11px] font-semibold ${cash === null ? "text-amber-700" : cash >= 0 ? "text-emerald-700" : "text-red-700"}`}>{cash === null ? "Cash unavailable" : `${formatCurrency(cash, "INR")} cash`}</p></div>; })}</div></div></div></Card>;
}
