import Link from "next/link";
import { ASSIGNMENT_PRIORITIES, ASSIGNMENT_STATUSES } from "@/lib/constants/assignments";
import type { DeadlineWriter } from "@/types/deadline";

const fieldClass = "h-10 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm text-slate-700 outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-500/10";

export function DeadlineFilters({ timing, status, priority, writerId, writers }: { timing?: string; status?: string; priority?: string; writerId?: string; writers: DeadlineWriter[] }) {
  const active = Boolean(timing || status || priority || writerId);
  return <form action="/deadlines" className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><div><label htmlFor="deadline-timing" className="sr-only">Timing</label><select id="deadline-timing" name="timing" defaultValue={timing ?? ""} className={fieldClass}><option value="">All deadlines</option><option value="overdue">Overdue</option><option value="today">Due today</option><option value="upcoming">Upcoming</option></select></div><div><label htmlFor="deadline-status" className="sr-only">Assignment status</label><select id="deadline-status" name="status" defaultValue={status ?? ""} className={fieldClass}><option value="">All statuses</option>{ASSIGNMENT_STATUSES.filter((item) => item.value === "new").map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></div><div><label htmlFor="deadline-priority" className="sr-only">Priority</label><select id="deadline-priority" name="priority" defaultValue={priority ?? ""} className={fieldClass}><option value="">All priorities</option>{ASSIGNMENT_PRIORITIES.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></div><div><label htmlFor="deadline-writer" className="sr-only">Writer</label><select id="deadline-writer" name="writer" defaultValue={writerId ?? ""} className={fieldClass}><option value="">All writers</option>{writers.map((writer) => <option key={writer.id} value={writer.id}>{writer.name}</option>)}</select></div></div><div className="mt-3 flex justify-end gap-2"><button type="submit" className="h-10 rounded-lg bg-slate-900 px-4 text-sm font-semibold text-white hover:bg-slate-700">Apply filters</button>{active && <Link href="/deadlines" className="inline-flex h-10 items-center rounded-lg px-3 text-sm font-medium text-slate-600 hover:bg-slate-100">Clear</Link>}</div></form>;
}
