import Link from "next/link";
import type { LucideIcon } from "lucide-react";
import { Building2, CircleUserRound, Coins, Mail, MessageCircle, Phone } from "lucide-react";
import { AssignmentWorkerStatusBadge } from "@/components/assignments/assignment-worker-status-badge";
import { Card } from "@/components/ui/card";
import { formatCurrency, formatDate, formatDateTime } from "@/lib/utils/format";
import type { WriterAssignment, WriterDetail, WriterPaymentHistory } from "@/types/writer";
import { WriterMoney } from "./writer-money";

function ProfileRow({ icon: Icon, label, value, href }: { icon: LucideIcon; label: string; value: string | null; href?: string }) {
  return <div className="flex gap-3 py-3"><span className="mt-0.5 flex size-8 shrink-0 items-center justify-center rounded-lg bg-slate-100 text-slate-500"><Icon aria-hidden="true" className="size-4" /></span><div className="min-w-0"><p className="text-xs font-medium uppercase tracking-wide text-slate-400">{label}</p>{value ? href ? <a href={href} className="mt-1 block break-words text-sm font-medium text-indigo-700 hover:underline">{value}</a> : <p className="mt-1 break-words text-sm font-medium text-slate-800">{value}</p> : <p className="mt-1 text-sm text-slate-400">Not provided</p>}</div></div>;
}

function WorkTable({ title, description, rows }: { title: string; description: string; rows: WriterAssignment[] }) {
  return <Card className="overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-semibold text-slate-900">{title}</h2><p className="mt-1 text-sm text-slate-500">{description}</p></div>{rows.length === 0 ? <p className="px-5 py-8 text-center text-sm text-slate-500">No records in this section.</p> : <div className="overflow-x-auto"><table className="min-w-[850px] w-full text-left"><thead className="border-b border-slate-200 bg-slate-50"><tr className="text-xs font-semibold uppercase tracking-wide text-slate-500"><th className="px-5 py-3">Assignment</th><th className="px-5 py-3">Work description</th><th className="px-5 py-3">Writer deadline</th><th className="px-5 py-3">Agreed cost</th><th className="px-5 py-3">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row) => <tr key={row.id} className="hover:bg-slate-50"><td className="px-5 py-4"><Link href={`/assignments/${row.assignment_id}`} className="font-semibold text-indigo-700 hover:underline">{row.task_code ?? "Unavailable task"}</Link><p className="mt-1 max-w-56 truncate text-sm text-slate-600">{row.assignment_title ?? "Assignment unavailable"}</p></td><td className="max-w-64 px-5 py-4 text-sm text-slate-600">{row.work_description || "No description"}</td><td className="px-5 py-4 text-sm text-slate-600">{row.worker_deadline ? formatDateTime(row.worker_deadline) : "No deadline"}</td><td className="px-5 py-4 text-sm font-medium text-slate-800">{formatCurrency(row.agreed_cost, row.currency)}</td><td className="px-5 py-4"><AssignmentWorkerStatusBadge status={row.status} />{row.delivered_at && <p className="mt-1 text-xs text-slate-500">Delivered {formatDateTime(row.delivered_at)}</p>}</td></tr>)}</tbody></table></div>}</Card>;
}

function PaymentTable({ rows }: { rows: WriterPaymentHistory[] }) {
  return <Card className="overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-semibold text-slate-900">Payment history</h2><p className="mt-1 text-sm text-slate-500">Payments recorded against this writer’s allocations.</p></div>{rows.length === 0 ? <p className="px-5 py-8 text-center text-sm text-slate-500">No writer payments recorded yet.</p> : <div className="overflow-x-auto"><table className="min-w-[820px] w-full text-left"><thead className="border-b border-slate-200 bg-slate-50"><tr className="text-xs font-semibold uppercase tracking-wide text-slate-500"><th className="px-5 py-3">Date</th><th className="px-5 py-3">Assignment</th><th className="px-5 py-3">Amount</th><th className="px-5 py-3">Method</th><th className="px-5 py-3">Account</th><th className="px-5 py-3">Reference</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row) => <tr key={row.id}><td className="px-5 py-4 text-sm text-slate-600">{formatDate(row.payment_date)}</td><td className="px-5 py-4">{row.assignment_id ? <Link href={`/assignments/${row.assignment_id}`} className="font-semibold text-indigo-700 hover:underline">{row.task_code ?? "Unavailable task"}</Link> : <span className="text-sm text-slate-400">Unavailable</span>}<p className="mt-1 max-w-56 truncate text-sm text-slate-500">{row.assignment_title}</p></td><td className="px-5 py-4 text-sm font-semibold text-slate-900">{formatCurrency(row.amount, row.currency)}</td><td className="px-5 py-4 text-sm text-slate-600">{row.payment_method || "Not specified"}</td><td className="px-5 py-4 text-sm text-slate-600">{row.account_name || "No account"}</td><td className="px-5 py-4 text-sm text-slate-600">{row.transaction_reference || "—"}</td></tr>)}</tbody></table></div>}</Card>;
}

export function WriterDetails({ writer }: { writer: WriterDetail }) {
  const metrics = [
    { label: "Total assigned", value: String(writer.total_assignments), detail: "All allocation records" },
    { label: "Active tasks", value: String(writer.active_assignments), detail: "Open allocations on new assignments" },
    { label: "Completed work", value: String(writer.completed_assignments), detail: "Writer or assignment delivered" },
  ];
  return <div className="space-y-6">
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{metrics.map((metric) => <Card key={metric.label} className="p-5"><p className="text-sm font-medium text-slate-500">{metric.label}</p><p className="mt-2 text-2xl font-semibold text-slate-900">{metric.value}</p><p className="mt-2 text-xs text-slate-500">{metric.detail}</p></Card>)}</div>
    <div className="grid gap-4 sm:grid-cols-3"><Card className="p-5"><p className="text-sm font-medium text-slate-500">Total agreed cost</p><div className="mt-3 text-lg font-semibold"><WriterMoney values={writer.total_agreed_cost} /></div><p className="mt-2 text-xs text-slate-500">Non-cancelled allocations</p></Card><Card className="p-5"><p className="text-sm font-medium text-slate-500">Total paid</p><div className="mt-3 text-lg font-semibold"><WriterMoney values={writer.total_paid} /></div><p className="mt-2 text-xs text-slate-500">Recorded writer payments</p></Card><Card className="p-5"><p className="text-sm font-medium text-slate-500">Total payable</p><div className="mt-3 text-lg"><WriterMoney values={writer.total_payable} emphasize /></div><p className="mt-2 text-xs text-slate-500">Agreed cost minus paid, by currency</p></Card></div>
    <Card className="overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-semibold text-slate-900">Writer profile</h2></div><div className="grid divide-y divide-slate-100 px-5 md:grid-cols-3 md:divide-x md:divide-y-0"><div className="md:pr-5"><ProfileRow icon={CircleUserRound} label="Name" value={writer.name} /><ProfileRow icon={Building2} label="Company" value={writer.company_name} /></div><div className="md:px-5"><ProfileRow icon={Mail} label="Email" value={writer.email} href={writer.email ? `mailto:${writer.email}` : undefined} /><ProfileRow icon={Phone} label="Phone" value={writer.phone} href={writer.phone ? `tel:${writer.phone}` : undefined} /></div><div className="md:pl-5"><ProfileRow icon={MessageCircle} label="WhatsApp" value={writer.whatsapp} href={writer.whatsapp ? `https://wa.me/${writer.whatsapp.replace(/\D/g, "")}` : undefined} /><ProfileRow icon={Coins} label="Preferred currency" value={writer.preferred_currency} /></div></div></Card>
    <WorkTable title="Active assignments" description="Open writer allocations on new assignments." rows={writer.active_allocations} />
    <WorkTable title="Completed work" description="Work delivered by the writer or completed through assignment delivery." rows={writer.completed_allocations} />
    {writer.other_allocations.length > 0 && <WorkTable title="Cancelled allocations" description="Historical allocations that were cancelled." rows={writer.other_allocations} />}
    <PaymentTable rows={writer.payments} />
  </div>;
}
